/*
# Premium Traders - Full Schema

## Overview
Complete schema for a premium fintech trading platform with manual deposits/withdrawals,
daily global OTP reward system, VIP membership, notifications, support tickets, and admin panel.

## New Tables
1. `profiles` - Extended user data (full name, username, phone, country, wallet, VIP, status)
2. `payment_methods` - Editable deposit payment methods (Bank, JazzCash, EasyPaisa, USDT)
3. `deposits` - Manual deposit requests with screenshot, reference, status
4. `withdrawals` - Manual withdrawal requests with status
5. `transactions` - Unified ledger of all wallet movements
6. `daily_otps` - One global OTP per day at 5PM server time
7. `reward_claims` - Per-user daily reward claim records
8. `vip_levels` - Configurable VIP tiers with requirements + benefits
9. `vip_history` - User VIP upgrade/downgrade history
10. `notifications` - User notifications with unread badge
11. `announcements` - Admin announcements / popup messages
12. `support_tickets` - User support tickets
13. `ticket_messages` - Messages within support tickets
14. `website_settings` - Single-row editable site config
15. `login_history` - User login attempts (success + failed)
16. `admin_activity_logs` - Admin action audit trail

## Security
- RLS enabled on every table.
- Owner-scoped CRUD for user tables (profiles, deposits, withdrawals, transactions, notifications, support_tickets, ticket_messages, reward_claims, vip_history, login_history).
- Public read for payment_methods (active only), vip_levels (enabled), website_settings, announcements (active).
- Admin writes gated by a custom `is_admin()` check using `raw_app_meta_data.role = 'admin'`.
- Owner columns default to `auth.uid()` so client inserts succeed without passing user_id.

## Notes
1. Wallet balance lives on `profiles.wallet_balance` and is updated via RPC `adjust_wallet` to keep it atomic.
2. VIP auto-upgrade handled in RPC `recompute_vip` called after deposit approval.
3. Daily OTP generated by RPC `get_or_create_today_otp` (idempotent).
4. Reward claim handled by RPC `claim_daily_reward` (atomic, prevents duplicates).
*/

-- ============================================================
-- PROFILES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text NOT NULL DEFAULT '',
  username text UNIQUE,
  email text,
  phone text,
  country text,
  profile_picture text,
  wallet_balance numeric(18,2) NOT NULL DEFAULT 0,
  total_deposits numeric(18,2) NOT NULL DEFAULT 0,
  total_withdrawals numeric(18,2) NOT NULL DEFAULT 0,
  total_rewards numeric(18,2) NOT NULL DEFAULT 0,
  vip_level int NOT NULL DEFAULT 0,
  account_status text NOT NULL DEFAULT 'active', -- active | suspended | banned
  last_login timestamptz,
  preferred_theme text NOT NULL DEFAULT 'dark', -- dark | light | midnight | emerald
  preferred_language text NOT NULL DEFAULT 'en', -- en | ur
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
CREATE POLICY "profiles_select_own" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Admin can read all profiles
DROP POLICY IF EXISTS "profiles_admin_select_all" ON public.profiles;
CREATE POLICY "profiles_admin_select_all" ON public.profiles FOR SELECT TO authenticated USING (
  coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false)
);

-- ============================================================
-- PAYMENT METHODS (public read of active)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.payment_methods (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL, -- Bank Account | JazzCash | EasyPaisa | USDT TRC20
  account_title text NOT NULL,
  account_number text NOT NULL,
  qr_code text, -- URL or data string
  instructions text,
  is_active boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.payment_methods ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "payment_methods_public_read" ON public.payment_methods;
CREATE POLICY "payment_methods_public_read" ON public.payment_methods FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "payment_methods_admin_write" ON public.payment_methods;
CREATE POLICY "payment_methods_admin_write" ON public.payment_methods FOR ALL TO authenticated
  USING (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false))
  WITH CHECK (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));

-- ============================================================
-- DEPOSITS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.deposits (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  payment_method_id uuid REFERENCES public.payment_methods(id) ON DELETE SET NULL,
  amount numeric(18,2) NOT NULL,
  reference_number text,
  screenshot_url text,
  status text NOT NULL DEFAULT 'pending', -- pending | approved | rejected
  admin_remarks text,
  reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.deposits ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_deposits_user ON public.deposits(user_id);
CREATE INDEX IF NOT EXISTS idx_deposits_status ON public.deposits(status);

DROP POLICY IF EXISTS "deposits_select_own" ON public.deposits;
CREATE POLICY "deposits_select_own" ON public.deposits FOR SELECT TO authenticated
  USING (auth.uid() = user_id OR coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));
DROP POLICY IF EXISTS "deposits_insert_own" ON public.deposits;
CREATE POLICY "deposits_insert_own" ON public.deposits FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "deposits_admin_update" ON public.deposits;
CREATE POLICY "deposits_admin_update" ON public.deposits FOR UPDATE TO authenticated
  USING (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false))
  WITH CHECK (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));

-- ============================================================
-- WITHDRAWALS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.withdrawals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  amount numeric(18,2) NOT NULL,
  payment_method text NOT NULL,
  account_details text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  admin_remarks text,
  reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.withdrawals ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_withdrawals_user ON public.withdrawals(user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawals_status ON public.withdrawals(status);

DROP POLICY IF EXISTS "withdrawals_select_own" ON public.withdrawals;
CREATE POLICY "withdrawals_select_own" ON public.withdrawals FOR SELECT TO authenticated
  USING (auth.uid() = user_id OR coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));
DROP POLICY IF EXISTS "withdrawals_insert_own" ON public.withdrawals;
CREATE POLICY "withdrawals_insert_own" ON public.withdrawals FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "withdrawals_admin_update" ON public.withdrawals;
CREATE POLICY "withdrawals_admin_update" ON public.withdrawals FOR UPDATE TO authenticated
  USING (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false))
  WITH CHECK (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));

-- ============================================================
-- TRANSACTIONS (unified ledger)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  type text NOT NULL, -- deposit | withdrawal | reward | bonus | vip
  amount numeric(18,2) NOT NULL, -- positive for credit, negative for debit
  status text NOT NULL DEFAULT 'completed',
  reference_id text,
  description text,
  related_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_transactions_user ON public.transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_type ON public.transactions(type);

DROP POLICY IF EXISTS "transactions_select_own" ON public.transactions;
CREATE POLICY "transactions_select_own" ON public.transactions FOR SELECT TO authenticated
  USING (auth.uid() = user_id OR coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));
DROP POLICY IF EXISTS "transactions_insert_own" ON public.transactions;
CREATE POLICY "transactions_insert_own" ON public.transactions FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- DAILY OTP (one global OTP per day)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.daily_otps (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  otp_code text NOT NULL,
  reward_date date NOT NULL UNIQUE,
  reward_time time NOT NULL DEFAULT '17:00',
  expires_at timestamptz NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.daily_otps ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "daily_otps_read_all" ON public.daily_otps;
CREATE POLICY "daily_otps_read_all" ON public.daily_otps FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "daily_otps_admin_write" ON public.daily_otps;
CREATE POLICY "daily_otps_admin_write" ON public.daily_otps FOR ALL TO authenticated
  USING (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false))
  WITH CHECK (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));

-- ============================================================
-- REWARD CLAIMS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.reward_claims (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  otp_code text NOT NULL,
  reward_amount numeric(18,2) NOT NULL,
  claim_date date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, claim_date)
);
ALTER TABLE public.reward_claims ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_reward_claims_user ON public.reward_claims(user_id);

DROP POLICY IF EXISTS "reward_claims_select_own" ON public.reward_claims;
CREATE POLICY "reward_claims_select_own" ON public.reward_claims FOR SELECT TO authenticated
  USING (auth.uid() = user_id OR coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));
DROP POLICY IF EXISTS "reward_claims_insert_own" ON public.reward_claims;
CREATE POLICY "reward_claims_insert_own" ON public.reward_claims FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- VIP LEVELS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.vip_levels (
  level int PRIMARY KEY,
  name text NOT NULL,
  required_deposit numeric(18,2) NOT NULL DEFAULT 0,
  required_withdrawal numeric(18,2) NOT NULL DEFAULT 0,
  benefits text,
  badge_color text NOT NULL DEFAULT '#D4AF37',
  icon text NOT NULL DEFAULT 'crown',
  is_enabled boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0
);
ALTER TABLE public.vip_levels ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "vip_levels_read_all" ON public.vip_levels;
CREATE POLICY "vip_levels_read_all" ON public.vip_levels FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "vip_levels_admin_write" ON public.vip_levels;
CREATE POLICY "vip_levels_admin_write" ON public.vip_levels FOR ALL TO authenticated
  USING (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false))
  WITH CHECK (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));

-- ============================================================
-- VIP HISTORY
-- ============================================================
CREATE TABLE IF NOT EXISTS public.vip_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  from_level int NOT NULL,
  to_level int NOT NULL,
  reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.vip_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "vip_history_select_own" ON public.vip_history;
CREATE POLICY "vip_history_select_own" ON public.vip_history FOR SELECT TO authenticated
  USING (auth.uid() = user_id OR coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));
DROP POLICY IF EXISTS "vip_history_insert_own" ON public.vip_history;
CREATE POLICY "vip_history_insert_own" ON public.vip_history FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- NOTIFICATIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL DEFAULT 'info', -- info | success | warning | error | announcement
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_notifications_user ON public.notifications(user_id);

DROP POLICY IF EXISTS "notifications_select_own" ON public.notifications;
CREATE POLICY "notifications_select_own" ON public.notifications FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "notifications_insert_own" ON public.notifications;
CREATE POLICY "notifications_insert_own" ON public.notifications FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "notifications_update_own" ON public.notifications;
CREATE POLICY "notifications_update_own" ON public.notifications FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- ANNOUNCEMENTS (public read of active)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.announcements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL DEFAULT 'info', -- info | popup | maintenance
  is_active boolean NOT NULL DEFAULT true,
  scheduled_for timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "announcements_public_read" ON public.announcements;
CREATE POLICY "announcements_public_read" ON public.announcements FOR SELECT TO anon, authenticated USING (is_active = true);
DROP POLICY IF EXISTS "announcements_admin_write" ON public.announcements;
CREATE POLICY "announcements_admin_write" ON public.announcements FOR ALL TO authenticated
  USING (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false))
  WITH CHECK (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));

-- ============================================================
-- SUPPORT TICKETS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.support_tickets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  subject text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'open', -- open | replied | closed
  priority text NOT NULL DEFAULT 'normal',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tickets_select_own" ON public.support_tickets;
CREATE POLICY "tickets_select_own" ON public.support_tickets FOR SELECT TO authenticated
  USING (auth.uid() = user_id OR coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));
DROP POLICY IF EXISTS "tickets_insert_own" ON public.support_tickets;
CREATE POLICY "tickets_insert_own" ON public.support_tickets FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "tickets_update_own" ON public.support_tickets;
CREATE POLICY "tickets_update_own" ON public.support_tickets FOR UPDATE TO authenticated
  USING (auth.uid() = user_id OR coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false))
  WITH CHECK (auth.uid() = user_id OR coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));

-- ============================================================
-- TICKET MESSAGES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.ticket_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  sender text NOT NULL DEFAULT 'user', -- user | admin
  message text NOT NULL,
  attachment_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.ticket_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ticket_messages_select_own" ON public.ticket_messages;
CREATE POLICY "ticket_messages_select_own" ON public.ticket_messages FOR SELECT TO authenticated
  USING (
    auth.uid() = user_id OR
    coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false)
  );
DROP POLICY IF EXISTS "ticket_messages_insert_own" ON public.ticket_messages;
CREATE POLICY "ticket_messages_insert_own" ON public.ticket_messages FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- WEBSITE SETTINGS (single row)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.website_settings (
  id int PRIMARY KEY DEFAULT 1,
  site_name text NOT NULL DEFAULT 'Premium Traders',
  logo_url text,
  favicon_url text,
  primary_color text NOT NULL DEFAULT '#D4AF37',
  secondary_color text NOT NULL DEFAULT '#0A0A0A',
  reward_percentage numeric(5,2) NOT NULL DEFAULT 20.00,
  reward_time time NOT NULL DEFAULT '17:00',
  reward_window_hours int NOT NULL DEFAULT 24,
  reward_system_enabled boolean NOT NULL DEFAULT true,
  min_withdrawal_deposit numeric(18,2) NOT NULL DEFAULT 500.00,
  min_withdrawal_amount numeric(18,2) NOT NULL DEFAULT 100.00,
  contact_phone text,
  contact_whatsapp text,
  contact_telegram text,
  contact_email text,
  contact_facebook text,
  contact_instagram text,
  maintenance_mode boolean NOT NULL DEFAULT false,
  CONSTRAINT single_row CHECK (id = 1)
);
ALTER TABLE public.website_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "settings_public_read" ON public.website_settings;
CREATE POLICY "settings_public_read" ON public.website_settings FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "settings_admin_write" ON public.website_settings;
CREATE POLICY "settings_admin_write" ON public.website_settings FOR ALL TO authenticated
  USING (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false))
  WITH CHECK (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));

-- ============================================================
-- LOGIN HISTORY
-- ============================================================
CREATE TABLE IF NOT EXISTS public.login_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  email text,
  ip_address text,
  user_agent text,
  success boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.login_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "login_history_select_own" ON public.login_history;
CREATE POLICY "login_history_select_own" ON public.login_history FOR SELECT TO authenticated
  USING (auth.uid() = user_id OR coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));
DROP POLICY IF EXISTS "login_history_insert_own" ON public.login_history;
CREATE POLICY "login_history_insert_own" ON public.login_history FOR INSERT TO authenticated WITH CHECK (true);

-- ============================================================
-- ADMIN ACTIVITY LOGS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.admin_activity_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action text NOT NULL,
  target text,
  details text,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.admin_activity_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_logs_admin_read" ON public.admin_activity_logs;
CREATE POLICY "admin_logs_admin_read" ON public.admin_activity_logs FOR SELECT TO authenticated
  USING (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));
DROP POLICY IF EXISTS "admin_logs_admin_insert" ON public.admin_activity_logs;
CREATE POLICY "admin_logs_admin_insert" ON public.admin_activity_logs FOR INSERT TO authenticated
  WITH CHECK (coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false));

-- ============================================================
-- SEED DATA
-- ============================================================
INSERT INTO public.website_settings (id) VALUES (1)
  ON CONFLICT (id) DO NOTHING;

INSERT INTO public.vip_levels (level, name, required_deposit, required_withdrawal, benefits, badge_color, icon, sort_order) VALUES
  (0, 'Bronze', 0, 0, 'Basic access, daily rewards', '#CD7F32', 'shield', 0),
  (1, 'Silver', 1000, 500, 'Lower withdrawal fees, priority support', '#C0C0C0', 'medal', 1),
  (2, 'Gold', 5000, 2500, 'Higher reward rate, exclusive gifts', '#D4AF37', 'crown', 2),
  (3, 'Platinum', 20000, 10000, 'Personal account manager', '#E5E4E2', 'gem', 3),
  (4, 'Diamond', 50000, 25000, 'VIP events, premium gifts', '#B9F2FF', 'diamond', 4),
  (5, 'Elite', 200000, 100000, 'Custom reward rates, private channel', '#FFD700', 'trophy', 5),
  (6, 'Legend', 500000, 250000, 'Lifetime benefits, founder status', '#9B59B6', 'star', 6)
ON CONFLICT (level) DO NOTHING;

INSERT INTO public.payment_methods (name, account_title, account_number, instructions, sort_order) VALUES
  ('Bank Account', 'Premium Traders Ltd', 'PK00MEPD0000000000000000', 'Transfer to the bank account and upload the receipt.', 0),
  ('JazzCash', 'Premium Traders', '03001234567', 'Send to JazzCash number and upload screenshot.', 1),
  ('EasyPaisa', 'Premium Traders', '03451234567', 'Send to EasyPaisa number and upload screenshot.', 2),
  ('USDT TRC20', 'Premium Traders', 'TXxxxxxxxxxxxxxxxxxxxxxxxx', 'Send USDT (TRC20) to the wallet address.', 3)
ON CONFLICT DO NOTHING;

-- ============================================================
-- RPC: adjust_wallet (atomic wallet update + transaction log)
-- ============================================================
CREATE OR REPLACE FUNCTION public.adjust_wallet(
  p_user_id uuid,
  p_amount numeric,
  p_type text,
  p_description text,
  p_reference_id text DEFAULT NULL,
  p_related_id uuid DEFAULT NULL
) RETURNS void AS $$
BEGIN
  UPDATE public.profiles
  SET wallet_balance = wallet_balance + p_amount,
      total_deposits = CASE WHEN p_type = 'deposit' AND p_amount > 0 THEN total_deposits + p_amount ELSE total_deposits END,
      total_withdrawals = CASE WHEN p_type = 'withdrawal' AND p_amount < 0 THEN total_withdrawals + ABS(p_amount) ELSE total_withdrawals END,
      total_rewards = CASE WHEN p_type = 'reward' AND p_amount > 0 THEN total_rewards + p_amount ELSE total_rewards END,
      updated_at = now()
  WHERE id = p_user_id;

  INSERT INTO public.transactions (user_id, type, amount, status, description, reference_id, related_id)
  VALUES (p_user_id, p_type, p_amount, 'completed', p_description, p_reference_id, p_related_id);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- RPC: recompute_vip (auto upgrade/downgrade based on totals)
-- ============================================================
CREATE OR REPLACE FUNCTION public.recompute_vip(p_user_id uuid) RETURNS void AS $$
DECLARE
  v_deposit numeric; v_withdrawal numeric; v_current int; v_new int;
BEGIN
  SELECT total_deposits, total_withdrawals, vip_level
  INTO v_deposit, v_withdrawal, v_current
  FROM public.profiles WHERE id = p_user_id;

  SELECT COALESCE(MAX(level), 0) INTO v_new
  FROM public.vip_levels
  WHERE is_enabled = true
    AND required_deposit <= v_deposit
    AND required_withdrawal <= v_withdrawal;

  IF v_new <> v_current THEN
    UPDATE public.profiles SET vip_level = v_new, updated_at = now() WHERE id = p_user_id;
    INSERT INTO public.vip_history (user_id, from_level, to_level, reason)
    VALUES (p_user_id, v_current, v_new, 'Automatic recomputation');
    INSERT INTO public.notifications (user_id, title, message, type)
    VALUES (p_user_id, 'VIP Level Updated',
      'Your VIP level changed from VIP ' || v_current || ' to VIP ' || v_new || '.', 'success');
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- RPC: get_or_create_today_otp (idempotent daily OTP)
-- ============================================================
CREATE OR REPLACE FUNCTION public.get_or_create_today_otp() RETURNS TABLE (otp_code text, reward_date date, expires_at timestamptz, is_active boolean) AS $$
DECLARE
  v_time time; v_pct numeric; v_enabled boolean; v_window int;
  v_otp text; v_date date; v_expires timestamptz;
BEGIN
  SELECT reward_time, reward_percentage, reward_system_enabled, reward_window_hours
  INTO v_time, v_pct, v_enabled, v_window
  FROM public.website_settings WHERE id = 1;

  IF NOT v_enabled THEN RETURN; END IF;

  v_date := current_date;
  SELECT otp_code, expires_at, is_active INTO v_otp, v_expires, v_enabled
  FROM public.daily_otps WHERE reward_date = v_date;

  IF v_otp IS NULL THEN
    v_otp := lpad(floor(random() * 1000000)::text, 6, '0');
    v_expires := (v_date + v_time)::timestamptz + (v_window || ' hours')::interval;
    INSERT INTO public.daily_otps (otp_code, reward_date, reward_time, expires_at, is_active)
    VALUES (v_otp, v_date, v_time, v_expires, true)
    ON CONFLICT (reward_date) DO UPDATE SET otp_code = EXCLUDED.otp_code;
  END IF;

  RETURN QUERY SELECT v_otp, v_date, v_expires, true;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- RPC: claim_daily_reward (atomic, prevents duplicates)
-- ============================================================
CREATE OR REPLACE FUNCTION public.claim_daily_reward(p_user_id uuid, p_otp text) RETURNS TABLE (success boolean, reward_amount numeric, message text) AS $$
DECLARE
  v_otp text; v_date date; v_expires timestamptz; v_active boolean;
  v_deposit numeric; v_reward numeric; v_pct numeric; v_enabled boolean;
  v_existing uuid; v_claimed date;
BEGIN
  SELECT reward_percentage, reward_system_enabled INTO v_pct, v_enabled FROM public.website_settings WHERE id = 1;
  IF NOT v_enabled THEN
    RETURN QUERY SELECT false, 0::numeric, 'Reward system is currently disabled.'::text;
    RETURN;
  END IF;

  SELECT otp_code, reward_date, expires_at, is_active INTO v_otp, v_date, v_expires, v_active
  FROM public.daily_otps WHERE reward_date = current_date;

  IF v_otp IS NULL OR v_active = false THEN
    RETURN QUERY SELECT false, 0::numeric, 'No active OTP for today.'::text;
    RETURN;
  END IF;

  IF now() > v_expires THEN
    RETURN QUERY SELECT false, 0::numeric, 'Today''s OTP has expired.'::text;
    RETURN;
  END IF;

  IF p_otp <> v_otp THEN
    RETURN QUERY SELECT false, 0::numeric, 'Invalid OTP. Please check and try again.'::text;
    RETURN;
  END IF;

  SELECT total_deposits INTO v_deposit FROM public.profiles WHERE id = p_user_id;
  IF v_deposit <= 0 THEN
    RETURN QUERY SELECT false, 0::numeric, 'You need at least one approved deposit to claim rewards.'::text;
    RETURN;
  END IF;

  SELECT id INTO v_existing FROM public.reward_claims WHERE user_id = p_user_id AND claim_date = v_date;
  IF v_existing IS NOT NULL THEN
    RETURN QUERY SELECT false, 0::numeric, 'You have already claimed today''s reward.'::text;
    RETURN;
  END IF;

  v_reward := ROUND((v_deposit * v_pct / 100), 2);

  INSERT INTO public.reward_claims (user_id, otp_code, reward_amount, claim_date)
  VALUES (p_user_id, p_otp, v_reward, v_date);

  PERFORM public.adjust_wallet(p_user_id, v_reward, 'reward', 'Daily OTP reward claimed', p_otp);

  INSERT INTO public.notifications (user_id, title, message, type)
  VALUES (p_user_id, 'Reward Claimed', 'You have successfully claimed Rs. ' || v_reward || ' daily reward.', 'success');

  RETURN QUERY SELECT true, v_reward, 'Reward claimed successfully!'::text;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- RPC: approve_deposit (admin action - atomic)
-- ============================================================
CREATE OR REPLACE FUNCTION public.approve_deposit(p_deposit_id uuid, p_admin_id uuid, p_remarks text DEFAULT NULL) RETURNS void AS $$
DECLARE
  v_user_id uuid; v_amount numeric; v_status text;
BEGIN
  SELECT user_id, amount, status INTO v_user_id, v_amount, v_status FROM public.deposits WHERE id = p_deposit_id;
  IF v_status <> 'pending' THEN RETURN; END IF;

  UPDATE public.deposits SET status = 'approved', admin_remarks = p_remarks, reviewed_by = p_admin_id, reviewed_at = now()
  WHERE id = p_deposit_id;

  PERFORM public.adjust_wallet(v_user_id, v_amount, 'deposit', 'Deposit approved', p_deposit_id::text, p_deposit_id);
  PERFORM public.recompute_vip(v_user_id);

  INSERT INTO public.notifications (user_id, title, message, type)
  VALUES (v_user_id, 'Deposit Approved', 'Your deposit of Rs. ' || v_amount || ' has been approved.', 'success');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- RPC: reject_deposit (admin action)
-- ============================================================
CREATE OR REPLACE FUNCTION public.reject_deposit(p_deposit_id uuid, p_admin_id uuid, p_remarks text DEFAULT NULL) RETURNS void AS $$
DECLARE
  v_user_id uuid; v_amount numeric; v_status text;
BEGIN
  SELECT user_id, amount, status INTO v_user_id, v_amount, v_status FROM public.deposits WHERE id = p_deposit_id;
  IF v_status <> 'pending' THEN RETURN; END IF;

  UPDATE public.deposits SET status = 'rejected', admin_remarks = p_remarks, reviewed_by = p_admin_id, reviewed_at = now()
  WHERE id = p_deposit_id;

  INSERT INTO public.notifications (user_id, title, message, type)
  VALUES (v_user_id, 'Deposit Rejected', 'Your deposit of Rs. ' || v_amount || ' was rejected. ' || COALESCE(p_remarks, ''), 'error');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- RPC: approve_withdrawal (admin action - atomic)
-- ============================================================
CREATE OR REPLACE FUNCTION public.approve_withdrawal(p_withdrawal_id uuid, p_admin_id uuid, p_remarks text DEFAULT NULL) RETURNS void AS $$
DECLARE
  v_user_id uuid; v_amount numeric; v_status text;
BEGIN
  SELECT user_id, amount, status INTO v_user_id, v_amount, v_status FROM public.withdrawals WHERE id = p_withdrawal_id;
  IF v_status <> 'pending' THEN RETURN; END IF;

  UPDATE public.withdrawals SET status = 'approved', admin_remarks = p_remarks, reviewed_by = p_admin_id, reviewed_at = now()
  WHERE id = p_withdrawal_id;

  PERFORM public.adjust_wallet(v_user_id, -v_amount, 'withdrawal', 'Withdrawal approved', p_withdrawal_id::text, p_withdrawal_id);

  INSERT INTO public.notifications (user_id, title, message, type)
  VALUES (v_user_id, 'Withdrawal Approved', 'Your withdrawal of Rs. ' || v_amount || ' has been approved.', 'success');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- RPC: reject_withdrawal (admin action)
-- ============================================================
CREATE OR REPLACE FUNCTION public.reject_withdrawal(p_withdrawal_id uuid, p_admin_id uuid, p_remarks text DEFAULT NULL) RETURNS void AS $$
DECLARE
  v_user_id uuid; v_amount numeric; v_status text;
BEGIN
  SELECT user_id, amount, status INTO v_user_id, v_amount, v_status FROM public.withdrawals WHERE id = p_withdrawal_id;
  IF v_status <> 'pending' THEN RETURN; END IF;

  UPDATE public.withdrawals SET status = 'rejected', admin_remarks = p_remarks, reviewed_by = p_admin_id, reviewed_at = now()
  WHERE id = p_withdrawal_id;

  INSERT INTO public.notifications (user_id, title, message, type)
  VALUES (v_user_id, 'Withdrawal Rejected', 'Your withdrawal of Rs. ' || v_amount || ' was rejected. ' || COALESCE(p_remarks, ''), 'error');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- TRIGGER: create profile on auth signup
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, username)
  VALUES (NEW.id, NEW.email, COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
          COALESCE(NEW.raw_user_meta_data->>'username', ''));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();